spring.datasource.url=jdbc:h2:mem:coxinhadb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# Permitir frames para carregar o console H2 no navegador
spring.headers.frame-options.disable=true
server.port=8080
