# Conexão com o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/coxinhadb?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456 # Coloque aqui a senha do seu MySQL

# Mostrar o SQL no terminal para o professor ver a funcionar
spring.jpa.show-sql=true

# O Hibernate vai criar/atualizar as tabelas automaticamente no MySQL
spring.jpa.hibernate.ddl-auto=update

# Porta do servidor
server.port=8080