# 1. Conexão com o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/coxinhadb?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# 2. O Segredo: Ensinar o Java a falar o dialeto do MySQL (Apague a linha do H2Dialect se ainda estiver lá)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.jpa.hibernate.ddl-auto=update

# 4. Mostrar os comandos no terminal do Java
spring.jpa.show-sql=true
server.port=8080